### ISSUE TITLE
有没有linux下的破解脚本？

### ISSUE THREAD

**Issue by wxb2dyj** [Hlittled/studio-3t-trial#1]

**Comment by Hlittled** [comment]
日常用Windows, Linux可以尝试一下[jar包](https://github.com/Hlittled/studio_3t_trial)打补丁的方式, 这个应该是通用的, 或者搜索一下名称包含`soduz3vqhnnja46uvu3szq--`类似字符串的文件, 删掉, 感觉应该可以.
